title: STAN.inc
description: Sofar, so good
remote_theme: poole/hyde
permalink: pretty
url: https://stam-ink.github.io
baseurl: /blog-draft
paginate: 1
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-feed